name: Premier_Test_Update_Version
description: ''
version: 1.0.4
author: finch.david@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: premiertestupdateversion
  parentArtefactID: finchdavidprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2025-12-15 06:52:38'
pipelines:
  pipelines/updated_iterator:
    name: validation_mapping
    description: ''
    author: finch.david@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-12-16 07:28:06'
    datasets:
      inputs:
      - datasets/iterator_input
      - datasets/validation_source
      outputs:
      - datasets/iterator_output
    subgraphs: []
    dependencies: {}
datasets:
  datasets/iterator_input:
    name: validation_rules
    description: ''
    author: finch.david@prophecy.io
    createdAt: '2025-12-15 07:03:34'
    mode: batch
    physicalDatasets:
      spark_guides_prod_3_pat:
        fabricId: 34673
        datasetType: Database
        description: ''
        author: finch.david@prophecy.io
        createdAt: '2025-12-15 07:03:34'
  datasets/validation_source:
    name: source_table
    description: ''
    author: finch.david@prophecy.io
    createdAt: '2025-12-15 07:06:37'
    mode: batch
    physicalDatasets:
      spark_guides_prod_3_pat:
        fabricId: 34673
        datasetType: Database
        description: ''
        author: finch.david@prophecy.io
        createdAt: '2025-12-15 07:06:37'
  datasets/iterator_output:
    name: validation_output
    description: ''
    author: finch.david@prophecy.io
    createdAt: '2025-12-16 09:15:17'
    mode: batch
    physicalDatasets:
      spark_guides_prod_3_pat:
        fabricId: 34673
        datasetType: Database
        description: ''
        author: finch.david@prophecy.io
        createdAt: '2025-12-16 09:15:18'
templates: {}
jobs:
  jobs/validation_mapping_job:
    name: validation_mapping_job
    description: ''
    fabricUID: 34673
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small_job
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/updated_iterator
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2025-12-16 19:58:24'
    author: finch.david@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-12-15 06:52:38'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-12-15T06:52:38.359089Z'
  name: plibMaven
  version: 8.15.1
  id: '687466265'
  createdAt: '2025-12-15T06:52:38.359089Z'
  type: plibMaven
- modifiedAt: '2025-12-15T06:52:38.359089Z'
  name: plibPypi
  version: 2.1.7
  id: '667873859'
  createdAt: '2025-12-15T06:52:38.359089Z'
  type: plibPypi
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.53
    isDefault: true
    author: null
    createdAt: '2025-12-15 06:52:09'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.10
    isDefault: true
    author: null
    createdAt: '2025-12-15 06:52:09'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
projectConfigurations:
  projectConfigurations/config:
    name: config
    description: null
    author: finch.david@prophecy.io
    createdAt: '2025-12-16 19:25:09'
